apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: roadmap-creator
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: roadmap.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: roadmap-creator
                port:
                  number: 80
